//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSozluk.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OperationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OperationMessages() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KSozluk.Domain.Resources.OperationMessages", typeof(OperationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Açıklama başarılı bir şekilde getirildi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionsGettedSuccessfully {
            get {
                return ResourceManager.GetString("DescriptionsGettedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email adresi bulunamadı! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tüm kelimeler başarıyla getirildi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GettedAllWords {
            get {
                return ResourceManager.GetString("GettedAllWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarıyla giriş yapıldı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LoginSuccessfull {
            get {
                return ResourceManager.GetString("LoginSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bu işlem için yetkiniz bulunmamaktadır! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PermissionFailure {
            get {
                return ResourceManager.GetString("PermissionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kelimeler başarıyla getirildi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WordsGettedSuccessfully {
            get {
                return ResourceManager.GetString("WordsGettedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifreyi yanlış girdiniz! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
